/**
 * Test fixtures — synthetic org profiles that exercise every code path.
 *
 * Four profiles:
 * - Healthy: well-run nonprofit, should score KEEP
 * - Neglected: abandoned CRM, should score SIMPLIFY/MIGRATE
 * - Misfit: inventory org on Salesforce, should score SIMPLIFY
 * - Broken: half the queries failed
 */
import type { BaselineResults } from '../src/audit/index.js';

export const healthyOrg: BaselineResults = {
  timestamp: '2026-03-07T00:00:00Z',
  apiVersion: 'v59.0',
  orientation: {
    totalObjects: 120,
    customObjects: [
      { name: 'Custom_Report__c', label: 'Custom Report' },
    ],
    standardObjectCounts: {
      Contact: 5000,
      Account: 1200,
      Opportunity: 800,
      Campaign: 25,
      ContentDocument: 150,
    },
    customObjectCounts: { Custom_Report__c: 50 },
    packages: [
      { NamespacePrefix: 'npsp', Name: 'Nonprofit Success Pack' },
      { NamespacePrefix: 'GW_Volunteers', Name: 'Volunteers for Salesforce' },
    ],
    npspDetected: true,
    v4sDetected: true,
    npcDetected: false,
    totalUsers: 10,
    activeUsers: 8,
    totalContacts: 5000,
    totalAccounts: 1200,
    limits: {
      DailyApiRequests: { Max: 15000, Remaining: 14000 },
      DataStorageMB: { Max: 1000, Remaining: 700 },
      FileStorageMB: { Max: 1000, Remaining: 800 },
    },
    apiUsagePercent: 6.7,
    storageUsedPercent: 30,
    profileCount: 4,
    permissionSetCount: 6,
    contentDocumentCount: 150,
  },
  adoption: {
    logins6m: [
      { userId: 'u1', loginCount: 120, lastLogin: '2026-03-06' },
      { userId: 'u2', loginCount: 90, lastLogin: '2026-03-06' },
      { userId: 'u3', loginCount: 60, lastLogin: '2026-03-05' },
      { userId: 'u4', loginCount: 45, lastLogin: '2026-03-04' },
      { userId: 'u5', loginCount: 30, lastLogin: '2026-03-03' },
      { userId: 'u6', loginCount: 20, lastLogin: '2026-02-28' },
      { userId: 'u7', loginCount: 15, lastLogin: '2026-02-25' },
      { userId: 'u8', loginCount: 10, lastLogin: '2026-02-20' },
    ],
    activeUserCount: 8,
    totalLicensedUsers: 10,
    adoptionRate: 80,
    topCreatorContact: { userId: 'u1', count: 200 },
    topCreatorOpportunity: { userId: 'u1', count: 150 },
    creationConcentration: 40,
    reportUsage: 85,
    dashboardUsage: 30,
    setupChanges6m: 45,
    setupChangeUsers: 3,
    lastSetupChange: '2026-03-01',
    adminGone: false,
  },
  relationship: {
    tasks6m: 600,
    events6m: 200,
    emailMessages6m: 1500,
    notes6m: 100,
    totalInteractions6m: 2400,
    contactsWithTasks: 800,
    contactsWithEvents: 300,
    engagementRate: 16,
    closedWonOpps12m: 300,
    oppsWithFollowUp: 250,
    stewardshipRate: 83,
  },
  dataHealth: {
    totalContacts: 5000,
    contactsFresh6m: 2500,
    contactsFresh12m: 3800,
    freshnessRate6m: 50,
    freshnessRate12m: 76,
    contactsWithEmail: 4200,
    contactsWithPhone: 3500,
    contactsWithAddress: 2800,
    emailCompletenessRate: 84,
    duplicateEmails: 30,
    duplicateRate: 0.7,
    contactsNeverModified: 400,
    neverModifiedRate: 8,
    opportunityBurstiness: 10,
    burstyMonths: 1,
    totalMonthsChecked: 12,
    fieldFillRates: [],
  },
  fundraising: {
    donationsByType: [
      { recordType: 'Donation', count: 700, totalAmount: 250000 },
      { recordType: 'Grant', count: 100, totalAmount: 500000 },
    ],
    totalDonations: 800,
    totalDonationAmount: 750000,
    monthlyDonations: [
      { year: 2025, month: 4, count: 50 },
      { year: 2025, month: 5, count: 55 },
      { year: 2025, month: 6, count: 60 },
      { year: 2025, month: 7, count: 65 },
      { year: 2025, month: 8, count: 70 },
      { year: 2025, month: 9, count: 75 },
      { year: 2025, month: 10, count: 80 },
      { year: 2025, month: 11, count: 100 },
      { year: 2025, month: 12, count: 120 },
      { year: 2026, month: 1, count: 50 },
      { year: 2026, month: 2, count: 45 },
      { year: 2026, month: 3, count: 30 },
    ],
    activeCampaigns: 8,
    campaignMembers6m: 2500,
    recurringDonationsActive: 45,
    npspFeatureUsage: {
      'Recurring Donations': true,
      'Household Accounts': true,
      'Affiliations': true,
      'Relationships': true,
      'Soft Credits': true,
      'Allocations (GAU)': true,
      'Engagement Plans': false,
      'Batch Data Import': true,
    },
    npspFeaturesUsed: 7,
    npspFeaturesTotal: 8,
  },
  volunteers: {
    activeVolunteers: 120,
    hoursLogged6m: 450,
    totalHoursWorked6m: 1800,
    activeJobs: 15,
    volunteersWithNoHours12m: 20,
    volunteerUtilisationRate: 83,
  },
  customisation: {
    customObjectDetails: [
      {
        name: 'Custom_Report__c',
        label: 'Custom Report',
        recordCount: 50,
        customFieldCount: 8,
      },
    ],
    emptyCustomObjects: 0,
    totalCustomFields: 35,
    maxCustomFieldsOnObject: { objectName: 'Contact', count: 20 },
    activeFlows: 8,
    activeValidationRules: 5,
    activeWorkflowRules: 3,
    staleAutomations: 1,
  },
  integration: {
    connectedApps: [
      { name: 'Mailchimp', description: 'Email marketing' },
    ],
    installedPackages: [
      { NamespacePrefix: 'npsp', Name: 'Nonprofit Success Pack' },
      { NamespacePrefix: 'GW_Volunteers', Name: 'Volunteers for Salesforce' },
    ],
    packageCategories: {
      crm: ['Nonprofit Success Pack'],
      email: [],
      forms: [],
      volunteer: ['Volunteers for Salesforce'],
      reporting: [],
      other: [],
    },
    totalIntegrations: 3,
  },
  errors: [],
  queriesAttempted: 80,
  queriesSucceeded: 80,
  aborted: false,
  abortReason: null,
};

export const neglectedOrg: BaselineResults = {
  timestamp: '2026-03-07T00:00:00Z',
  apiVersion: 'v59.0',
  orientation: {
    totalObjects: 100,
    customObjects: [
      { name: 'Old_Project__c', label: 'Old Project' },
      { name: 'Legacy_Data__c', label: 'Legacy Data' },
      { name: 'Unused_Object__c', label: 'Unused Object' },
    ],
    standardObjectCounts: {
      Contact: 4800,
      Account: 900,
      Opportunity: 340,
      Campaign: 5,
      ContentDocument: 20,
    },
    customObjectCounts: {
      Old_Project__c: 150,
      Legacy_Data__c: 0,
      Unused_Object__c: 0,
    },
    packages: [
      { NamespacePrefix: 'npsp', Name: 'Nonprofit Success Pack' },
    ],
    npspDetected: true,
    v4sDetected: false,
    npcDetected: false,
    totalUsers: 10,
    activeUsers: 2,
    totalContacts: 4800,
    totalAccounts: 900,
    limits: {
      DailyApiRequests: { Max: 15000, Remaining: 14900 },
      DataStorageMB: { Max: 500, Remaining: 300 },
      FileStorageMB: { Max: 500, Remaining: 400 },
    },
    apiUsagePercent: 0.7,
    storageUsedPercent: 40,
    profileCount: 3,
    permissionSetCount: 2,
    contentDocumentCount: 20,
  },
  adoption: {
    logins6m: [
      { userId: 'u1', loginCount: 180, lastLogin: '2026-03-06' },
      { userId: 'u2', loginCount: 12, lastLogin: '2026-02-15' },
    ],
    activeUserCount: 2,
    totalLicensedUsers: 10,
    adoptionRate: 20,
    topCreatorContact: { userId: 'u1', count: 280 },
    topCreatorOpportunity: { userId: 'u1', count: 100 },
    creationConcentration: 95,
    reportUsage: 0,
    dashboardUsage: 0,
    setupChanges6m: 0,
    setupChangeUsers: 0,
    lastSetupChange: '2024-06-15',
    adminGone: true,
  },
  relationship: {
    tasks6m: 5,
    events6m: 0,
    emailMessages6m: 0,
    notes6m: 2,
    totalInteractions6m: 7,
    contactsWithTasks: 5,
    contactsWithEvents: 0,
    engagementRate: 0.1,
    closedWonOpps12m: 50,
    oppsWithFollowUp: 2,
    stewardshipRate: 4,
  },
  dataHealth: {
    totalContacts: 4800,
    contactsFresh6m: 120,
    contactsFresh12m: 400,
    freshnessRate6m: 2.5,
    freshnessRate12m: 8.3,
    contactsWithEmail: 2400,
    contactsWithPhone: 1200,
    contactsWithAddress: 800,
    emailCompletenessRate: 50,
    duplicateEmails: 180,
    duplicateRate: 7.5,
    contactsNeverModified: 3200,
    neverModifiedRate: 66.7,
    opportunityBurstiness: 75,
    burstyMonths: 9,
    totalMonthsChecked: 12,
    fieldFillRates: [],
  },
  fundraising: {
    donationsByType: [
      { recordType: 'Donation', count: 340, totalAmount: 87000 },
    ],
    totalDonations: 340,
    totalDonationAmount: 87000,
    monthlyDonations: [
      { year: 2025, month: 11, count: 200 },
      { year: 2025, month: 12, count: 120 },
      { year: 2026, month: 1, count: 20 },
    ],
    activeCampaigns: 0,
    campaignMembers6m: 0,
    recurringDonationsActive: 0,
    npspFeatureUsage: {
      'Recurring Donations': false,
      'Household Accounts': true,
      'Affiliations': false,
      'Relationships': false,
      'Soft Credits': false,
      'Allocations (GAU)': false,
      'Engagement Plans': false,
      'Batch Data Import': false,
    },
    npspFeaturesUsed: 1,
    npspFeaturesTotal: 8,
  },
  volunteers: null,
  customisation: {
    customObjectDetails: [
      {
        name: 'Old_Project__c',
        label: 'Old Project',
        recordCount: 150,
        customFieldCount: 25,
      },
      {
        name: 'Legacy_Data__c',
        label: 'Legacy Data',
        recordCount: 0,
        customFieldCount: 15,
      },
      {
        name: 'Unused_Object__c',
        label: 'Unused Object',
        recordCount: 0,
        customFieldCount: 8,
      },
    ],
    emptyCustomObjects: 2,
    totalCustomFields: 98,
    maxCustomFieldsOnObject: { objectName: 'Contact', count: 55 },
    activeFlows: 12,
    activeValidationRules: 8,
    activeWorkflowRules: 6,
    staleAutomations: 10,
  },
  integration: {
    connectedApps: [],
    installedPackages: [
      { NamespacePrefix: 'npsp', Name: 'Nonprofit Success Pack' },
    ],
    packageCategories: {
      crm: ['Nonprofit Success Pack'],
      email: [],
      forms: [],
      volunteer: [],
      reporting: [],
      other: [],
    },
    totalIntegrations: 1,
  },
  errors: [],
  queriesAttempted: 75,
  queriesSucceeded: 72,
  aborted: false,
  abortReason: null,
};

export const misfitOrg: BaselineResults = {
  timestamp: '2026-03-07T00:00:00Z',
  apiVersion: 'v59.0',
  orientation: {
    totalObjects: 110,
    customObjects: [
      { name: 'Item__c', label: 'Donated Item' },
      { name: 'Safety_Check__c', label: 'Safety Check' },
      { name: 'Referral__c', label: 'Referral' },
      { name: 'Warehouse_Location__c', label: 'Warehouse Location' },
      { name: 'Volunteer_Shift__c', label: 'Volunteer Shift' },
    ],
    standardObjectCounts: {
      Contact: 2000,
      Account: 400,
      Opportunity: 89,
      Campaign: 2,
      ContentDocument: 10,
    },
    customObjectCounts: {
      Item__c: 2847,
      Safety_Check__c: 4102,
      Referral__c: 1203,
      Warehouse_Location__c: 3,
      Volunteer_Shift__c: 0,
    },
    packages: [
      { NamespacePrefix: 'npsp', Name: 'Nonprofit Success Pack' },
      { NamespacePrefix: 'GW_Volunteers', Name: 'Volunteers for Salesforce' },
    ],
    npspDetected: true,
    v4sDetected: true,
    npcDetected: false,
    totalUsers: 8,
    activeUsers: 3,
    totalContacts: 2000,
    totalAccounts: 400,
    limits: {
      DailyApiRequests: { Max: 15000, Remaining: 14500 },
      DataStorageMB: { Max: 500, Remaining: 200 },
      FileStorageMB: { Max: 500, Remaining: 350 },
    },
    apiUsagePercent: 3.3,
    storageUsedPercent: 60,
    profileCount: 3,
    permissionSetCount: 4,
    contentDocumentCount: 10,
  },
  adoption: {
    logins6m: [
      { userId: 'u1', loginCount: 200, lastLogin: '2026-03-06' },
      { userId: 'u2', loginCount: 45, lastLogin: '2026-03-04' },
      { userId: 'u3', loginCount: 8, lastLogin: '2026-02-10' },
    ],
    activeUserCount: 3,
    totalLicensedUsers: 8,
    adoptionRate: 37.5,
    topCreatorContact: { userId: 'u1', count: 412 },
    topCreatorOpportunity: { userId: 'u1', count: 80 },
    creationConcentration: 85,
    reportUsage: 5,
    dashboardUsage: 0,
    setupChanges6m: 0,
    setupChangeUsers: 0,
    lastSetupChange: '2025-01-20',
    adminGone: true,
  },
  relationship: {
    tasks6m: 20,
    events6m: 5,
    emailMessages6m: 0,
    notes6m: 10,
    totalInteractions6m: 35,
    contactsWithTasks: 15,
    contactsWithEvents: 5,
    engagementRate: 0.75,
    closedWonOpps12m: 30,
    oppsWithFollowUp: 0,
    stewardshipRate: 0,
  },
  dataHealth: {
    totalContacts: 2000,
    contactsFresh6m: 300,
    contactsFresh12m: 600,
    freshnessRate6m: 15,
    freshnessRate12m: 30,
    contactsWithEmail: 800,
    contactsWithPhone: 600,
    contactsWithAddress: 400,
    emailCompletenessRate: 40,
    duplicateEmails: 45,
    duplicateRate: 5.6,
    contactsNeverModified: 1100,
    neverModifiedRate: 55,
    opportunityBurstiness: 60,
    burstyMonths: 7,
    totalMonthsChecked: 12,
    fieldFillRates: [],
  },
  fundraising: {
    donationsByType: [
      { recordType: 'Donation', count: 60, totalAmount: 45000 },
      { recordType: 'In-Kind', count: 29, totalAmount: 0 },
    ],
    totalDonations: 89,
    totalDonationAmount: 45000,
    monthlyDonations: [
      { year: 2025, month: 11, count: 40 },
      { year: 2025, month: 12, count: 30 },
      { year: 2026, month: 1, count: 10 },
      { year: 2026, month: 2, count: 9 },
    ],
    activeCampaigns: 1,
    campaignMembers6m: 50,
    recurringDonationsActive: 0,
    npspFeatureUsage: {
      'Recurring Donations': false,
      'Household Accounts': true,
      'Affiliations': false,
      'Relationships': false,
      'Soft Credits': false,
      'Allocations (GAU)': false,
      'Engagement Plans': false,
      'Batch Data Import': false,
    },
    npspFeaturesUsed: 1,
    npspFeaturesTotal: 8,
  },
  volunteers: {
    activeVolunteers: 620,
    hoursLogged6m: 0,
    totalHoursWorked6m: 0,
    activeJobs: 0,
    volunteersWithNoHours12m: 620,
    volunteerUtilisationRate: 0,
  },
  customisation: {
    customObjectDetails: [
      { name: 'Item__c', label: 'Donated Item', recordCount: 2847, customFieldCount: 18 },
      { name: 'Safety_Check__c', label: 'Safety Check', recordCount: 4102, customFieldCount: 12 },
      { name: 'Referral__c', label: 'Referral', recordCount: 1203, customFieldCount: 15 },
      { name: 'Warehouse_Location__c', label: 'Warehouse Location', recordCount: 3, customFieldCount: 6 },
      { name: 'Volunteer_Shift__c', label: 'Volunteer Shift', recordCount: 0, customFieldCount: 10 },
    ],
    emptyCustomObjects: 1,
    totalCustomFields: 85,
    maxCustomFieldsOnObject: { objectName: 'Contact', count: 30 },
    activeFlows: 5,
    activeValidationRules: 3,
    activeWorkflowRules: 2,
    staleAutomations: 4,
  },
  integration: {
    connectedApps: [],
    installedPackages: [
      { NamespacePrefix: 'npsp', Name: 'Nonprofit Success Pack' },
      { NamespacePrefix: 'GW_Volunteers', Name: 'Volunteers for Salesforce' },
    ],
    packageCategories: {
      crm: ['Nonprofit Success Pack'],
      email: [],
      forms: [],
      volunteer: ['Volunteers for Salesforce'],
      reporting: [],
      other: [],
    },
    totalIntegrations: 2,
  },
  errors: [],
  queriesAttempted: 78,
  queriesSucceeded: 75,
  aborted: false,
  abortReason: null,
};

export const brokenOrg: BaselineResults = {
  timestamp: '2026-03-07T00:00:00Z',
  apiVersion: 'v59.0',
  orientation: {
    totalObjects: 80,
    customObjects: [],
    standardObjectCounts: {
      Contact: 100,
      Account: 50,
      Opportunity: 0,
      Campaign: 0,
      ContentDocument: 0,
    },
    customObjectCounts: {},
    packages: [],
    npspDetected: false,
    v4sDetected: false,
    npcDetected: false,
    totalUsers: 5,
    activeUsers: 1,
    totalContacts: 100,
    totalAccounts: 50,
    limits: null,
    apiUsagePercent: null,
    storageUsedPercent: null,
    profileCount: 2,
    permissionSetCount: 1,
    contentDocumentCount: 0,
  },
  adoption: null,
  relationship: null,
  dataHealth: null,
  fundraising: null,
  volunteers: null,
  customisation: null,
  integration: null,
  errors: [
    { queryId: 'Q-ADO-01', category: 'adoption', error: 'INSUFFICIENT_ACCESS', timestamp: '2026-03-07T00:00:01Z' },
    { queryId: 'Q-ADO-02', category: 'adoption', error: 'INSUFFICIENT_ACCESS', timestamp: '2026-03-07T00:00:02Z' },
    { queryId: 'Q-REL-01', category: 'relationship', error: 'INSUFFICIENT_ACCESS', timestamp: '2026-03-07T00:00:03Z' },
    { queryId: 'Q-REL-02', category: 'relationship', error: 'INSUFFICIENT_ACCESS', timestamp: '2026-03-07T00:00:04Z' },
    { queryId: 'Q-DAT-01', category: 'data-health', error: 'INSUFFICIENT_ACCESS', timestamp: '2026-03-07T00:00:05Z' },
    { queryId: 'Q-FUN-01', category: 'fundraising', error: 'INSUFFICIENT_ACCESS', timestamp: '2026-03-07T00:00:06Z' },
    { queryId: 'Q-CUS-01', category: 'customisation', error: 'INSUFFICIENT_ACCESS', timestamp: '2026-03-07T00:00:07Z' },
    { queryId: 'Q-INT-01', category: 'integration', error: 'INSUFFICIENT_ACCESS', timestamp: '2026-03-07T00:00:08Z' },
  ],
  queriesAttempted: 40,
  queriesSucceeded: 12,
  aborted: true,
  abortReason: 'Error rate exceeded 60% after adoption queries.',
};
